default_language_version:
  python: python
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: pretty-format-json
        args: ['--autofix', '--indent 2', ]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--config", "./api/pyproject.toml", . ]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
      - id: pylama
        additional_dependencies:
          - mccabe
          - pycodestyle
          - pyflakes
          - radon
          - toml
        args: ['-o', './api/pyproject.toml']
  - repo: https://github.com/PyCQA/bandit
    rev: master
    hooks:
      - id: bandit
        args: ['--skip', 'B101']
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
        entry: safety
        args: [check]
        files: ./api/requirements-build.txt
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: ['--ignore-words', 'codespell-ignore-words.txt']
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: sh -c "cd ./api/ && make check-migrations"
        files: models/*.*\.py$
        stages: [commit]
